# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
